version: '3.6'

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./:/etc/letsencrypt
    ports:
      # IPv4にbindしないとCAAレコードを要求され、詰む。
      - "160.16.233.95:80:80"
      - "160.16.233.95:443:443"
