# ゾーンごとに conf/valuedomain-<ゾーン名>.ini として配置する。
# 例: conf/valuedomain-hexe.net.ini
dns_valuedomain_api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dns_valuedomain_domain=example.com
